DROP TABLE DIM_TIME;
CREATE TABLE DIM_TIME
AS
SELECT 
   n AS SK_TIME,
   TO_NUMBER(TO_CHAR(to_date(n,'SSSSS'),'HH24')) AS HOUR,
   TO_NUMBER(TO_CHAR(to_date(n,'SSSSS'),'MI'))   AS MINUTE,
   TO_NUMBER(TO_CHAR(to_date(n,'SSSSS'),'SS'))   AS SECOND,
   TO_CHAR(to_date(n,'SSSSS'),'HH24') || ':' || TO_CHAR(to_date(n,'SSSSS'),'MI') || ':' || TO_CHAR(to_date(n,'SSSSS'),'SS') AS TIME,
   CASE WHEN n BETWEEN 0 AND 21599 THEN 'DAWN'
        WHEN n BETWEEN 21600 AND 43199 THEN 'MORNING'
        WHEN n BETWEEN 43200 AND 64799 THEN 'AFTERNOON'
        ELSE 'NIGHT'
   END AS PERIOD,
   SYSDATE AS LOAD_DATE
FROM (
   SELECT
      level-1 n
   FROM 
      DUAL
   CONNECT BY LEVEL <= 86400
);
