DECLARE
V_START DATE := TO_DATE('01/01/1950','DD/MM/YYYY'); --ALTER HERE YOUR START DATE
V_END   DATE := TO_DATE('31/12/2015','DD/MM/YYYY'); --ALTER HERE YOUR END DATE

BEGIN

EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT =   ''DD/MM/YYYY'''; -- ALTER HERE YOUR DATE MASK
--EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_LANGUAGE = ''BRAZILIAN PORTUGUESE'''; -- ALTER HERE YOUR REGION LANGUAGE
EXECUTE IMMEDIATE 'TRUNCATE TABLE DIM_TIME_DATA';

WHILE V_START <= V_END 
LOOP
INSERT INTO DIM_TIME_DATE
VALUES 
(
  --SK_DATE
  TO_NUMBER(TO_CHAR(V_START,'YYYYQMMDD')), 
  --DATE
  TO_DATE(V_START,'DD/MM/YYYY'),
  --NR_MONTH
  TO_NUMBER(TO_CHAR(V_START,'MM')),
  --DS_MONTH
  TO_CHAR(V_START,'Month'),
  --AB_MONTH
  TO_CHAR(V_START,'MON'),
  --ID_MONTH
  TO_NUMBER(TO_CHAR(V_START,'YYYY') || TO_CHAR(V_START,'Q') || TO_CHAR(V_START,'MM')),
  --NR_QUARTER
  TO_NUMBER(TO_CHAR(V_START,'Q')),
  --DS_QUARTER
  'T'||TO_CHAR(V_START,'Q'),
  --ID_QUARTER
  TO_NUMBER(TO_CHAR(V_START,'YYYY') || TO_CHAR(V_START,'Q')),
  --DS_YEAR
  TO_CHAR(V_START,'YYYY'),
  --ID_YEAR
  TO_NUMBER(TO_CHAR(V_START,'YYYY')),
  --LOAD_DATE
  TO_DATE(SYSDATE,'DD/MM/YYYY')
);
V_START := V_START+1;
END LOOP;
COMMIT;
END;
/
